keys:
  - &admin_chfoidl AE6E082A2BFDEAED54DA0E1A1A177C39837CF98C
  - &host_chf-workstation cabe7a49813b43d68cc86714217fd8039d2474e0
  - &host_tp-p14s A9F73A318B64BD75D26EBAED4691114D30F8CADD
  - &host_wunder-workstation 64469DA976F538FEB111DB27BB01D4FC230948CC
creation_rules:
  - path_regex: secrets/shared/secrets.yaml$
    key_groups:
    - pgp:
      - *admin_chfoidl
      - *host_chf-workstation
      - *host_tp-p14s
      - *host_wunder-workstation
  - path_regex: systems/chf-workstation/secrets.yaml$
    key_groups:
    - pgp:
      - *admin_chfoidl
      - *host_chf-workstation
  - path_regex: systems/tp-p14s/secrets.yaml$
    key_groups:
    - pgp:
      - *admin_chfoidl
      - *host_tp-p14s
  - path_regex: systems/wunder-workstation/secrets.yaml$
    key_groups:
    - pgp:
      - *admin_chfoidl
      - *host_wunder-workstation
