keys:
  - &admin_chfoidl F65267BDED8531DCD3D4F910196C046D738C6382
  - &host_chf-workstation cabe7a49813b43d68cc86714217fd8039d2474e0
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - pgp:
      - *admin_chfoidl
      - *host_chf-workstation
