#!/bin/sh

# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000

export PNPM_HOME=$HOME/.local/share/pnpm
export GOPATH=$HOME/.local/share/go

export PATH="$HOME/.local/bin":$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export PATH=$PNPM_HOME:$PATH

#export MANPAGER='nvim +Man!'
export MANWIDTH=999

export XKB_DEFAULT_LAYOUT=de
export XKB_DEFAULT_OPTIONS=caps:escape

export WLR_NO_HARDWARE_CURSORS=1
export WLR_DRM_NO_MODIFIERS=1
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
export LIBVA_DRIVER_NAME=radeonsi
export VDPAU_DRIVER=radeonsi

export DOCKER_BUILDKIT=1
export NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"
